### ISSUE TITLE
Code Coverage should be visible

### ISSUE THREAD

**Issue by SarahAugustinowski** [uni-bremen-agst/SEE#672]
The Axivion developers want to see the Code-Coverage in SEE. The XML-Testreport will be used to parse the test-information into SEE and its graphelements.
_(JaCoCo with Gradle-build is used by Axivion at the moment)_

Discarded ideas were: CSV-Import and Show the HTML-Report. 

TODO:
- [x] Parse XML
- [x] write Graph.Nodes in dictionary, with Source as Index
- [x] Find corresponding nodes in dictionary
- [x] set Node Attributes with setFloat
- [x] run Importer when Loading Graph
- [x] include Test-Case

Ideal additions:
- [ ] change between different Test-tools
- [ ] implement https://doc.froglogic.com/squish-coco/latest/

**Comment by koschke** [comment]
The option to view it as a HTML file in the browser may be a useful add-on and would likely work without any coding on our side if the just knows the URL of the JaCoCo tool. But it is not a replacement of the first option to import it via CSV because as a user I want to see the data in my code city.
