### ISSUE TITLE
SEE.Net.ClientActionNetwork.GetFile should not submit the room password in the URL

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#750]

**Comment by tinxx** [comment]
I have replaced the separate plaintext authorization for SEE clients in the backend with a dedicated user per game server in [40defde2](https://github.com/uni-bremen-agst/SEE/commit/40defde24e290dbde342aca18a4bbf31b60d9b4f).
The client-side authentication has been implemented in [b7686324](https://github.com/uni-bremen-agst/SEE/commit/b76863247ff524de6d070cb6968d9ec4c96360c2)

While this is not yet merged, the issue was only occurred in commented-out code, so I'm gonna close this issue.
